#!/usr/bin/env bash

set -e

###
# functions
###

installed() { hash $1 &> /dev/null; }

###
# globals
###
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

###
# installer
###

# Homebrew - https://github.com/Homebrew/homebrew
if ! installed brew; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Brew Bundle - https://github.com/Homebrew/homebrew-bundle
brew tap Homebrew/bundle
brew bundle

# Dotbot install
./install

# global 
if [[ -f ~/.gitignore_global ]]; then
	git config --global core.excludesfile ~/.gitignore_global
fi

if (( $+commands[subl] )); then
	git config --global core.editor "subl -n -w"
fi

# oh-my-zsh
if ! [[ -d $HOME/.oh-my-zsh ]]; then
  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
fi

# dockutil
dockutil --remove 'Launchpad'
dockutil --remove 'Safari'
dockutil --remove 'Mail'
dockutil --remove 'Contacts'
dockutil --remove 'Calendar'
dockutil --remove 'Notes'
dockutil --remove 'Reminders'
dockutil --remove 'Maps'
dockutil --remove 'Photos'
dockutil --remove 'Messages'
dockutil --remove 'FaceTime'
dockutil --remove 'iTunes'
dockutil --remove 'iBooks'
dockutil --remove 'App Store'
dockutil --remove 'System Preferences'
dockutil --add '/Applications/' --display folder --before 'Downloads'
dockutil --add '~/Documents/' --display folder --before 'Downloads'
dockutil --add /Applications/Firefox.app --position 2
dockutil --add /Applications/Microsoft\ Outlook.app --position 3
dockutil --add /Applications/iTerm.app --position 4
dockutil --add /Applications/Visual\ Studio\ Code.app --position 5
dockutil --add /Applications/Spotify.app --position 6
dockutil --add /Applications/Evernote.app --position 7
dockutil --add /Applications/Amazon\ Chime.app --position 8
dockutil --add /Applications/Discord.app --position 9
dockutil --add /Applications/IntelliJ\ IDEA.app --position 10




